services:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: keycloak
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - DB_VENDOR=h2
  #     - KEYCLOAK_IMPORT=/tmp/realm.json
  #   volumes:
  #     - ./keycloak/realm.json:/tmp/realm.json
  #   ports:
  #     - "8080:8080"
  #   command:
  #     - start-dev
  auth-server:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/lua:/etc/nginx/lua
    depends_on:
      - category-service
      - product-service

  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    container_name: category-service
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
